[stream_to_query]
stream = "AODataStream"
# stream = "PICOSTREAM"
# stream = "ct_bic"
buffer_size_s = 0.5
[lsl_outlet]
name="decoder_output"
nominal_freq_hz = 5500      # either a float or "derive" -> take same as input
format = "float32"
type="decoder_output"
initial_delay_s = 0           # time to wait until first sample is passed further down the pipe, pass zeros until then
